# NOTE: For binary features, v=p(1-p); if v=0.01 => p=0.01 or 0.99
score_function: "chi2"
n_feature_selection: 1000
reduction_function: null
n_feature_reduction: 1000
random_state: 42
variance_threshold: 0.01
correlation_threshold: false
sampling_type: "random"
imbalance_correction: false
test_size: 0.3
cross_validation: true
n_splits: 5
phenotype_sample_size_threshold: 20
minor_class_sample_size_threshold: 10
shap_max_display: 10
scoring:
  [
    "accuracy",
    "balanced_accuracy",
    "precision",
    "recall",
    "f1",
    "roc_auc",
    "matthews_corrcoef",
  ]
log_models: false
